### ISSUE TITLE
TouchKitMapAnt works Only with Firefox

### ISSUE THREAD

**Issue by gbuompastore** [parttio/touchkit-example#1]
Hi Matti I've notice that the new TouckKit example, works only on firefox.

java.lang.IllegalArgumentException: Illegal character in path at index 10: deferredjs\F7B66AFF78B95938200500C14E19DB8B\1.cache.js
	at java.net.URI.create(URI.java:852)
	at java.net.URI.resolve(URI.java:1036)
	at org.vaadin.touchkit.settings.TouchKitSettings.modifyBootstrapPage(TouchKitSettings.java:266)

Maybe something related with file path?

**My Configuration:**
S.O Windows 10 64-bit
Eclipse 64bit
Vaadin 8 / Jetty

**My Patch**
```
 if (cachedFilesStarted) {
   readLine = readLine.trim();
   if (!readLine.isEmpty()) {
           if(readLine.contains("\\"))
               readLine=readLine.replace("\\", "/");
        URI resolved = base.resolve(readLine);
         resources.add(resolved.toString());
          }
    }
```

**Comment by mstahv** [comment]
The issue has probably been forever, also in the official Vaadin TouchKit, but now with the recent versions it happens to break Chrome altogether (when using Windows as a development machine).

This fix should do it: https://github.com/parttio/touchkit/commit/42f1625382db75af819e8770158e7cdc146a4c6e I hope somebody with Windows can verify.

**Comment by gbuompastore** [comment]
I'll try It as soon as possible..And i give You a feedback anyaway!


Il 13 Feb 2018 16:50, "Matti Tahvonen" <notifications@github.com> ha
scritto:
